name: ccm
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
#  flutter_slider_drawer: ^2.1.3
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.6.1
  animated_bottom_navigation_bar: ^1.3.0
  material_symbols_icons: ^4.2713.0
  banner_carousel: ^1.2.1
  ionicons: ^0.2.2
  flutter_contacts: ^1.1.7+1
  contacts_service: ^0.6.3
  permission_handler: ^11.3.1
  iconly: ^1.0.1
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  http: ^1.2.1
  intl: ^0.19.0
  phone_number: ^2.0.1

  flutter_secure_storage: ^4.2.1
  animated_snack_bar: ^0.4.0
  flutter_staggered_animations: ^1.1.1
  stylish_dialog: ^1.0.2
  image_picker: ^1.1.2
#  flutter_staggered_grid_view: ^0.7.0
#  graphql_flutter: ^5.2.0-beta.6
#  graphql: ^5.2.0-beta.6
#  hive: ^2.2.3
#  path_provider: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
